### ISSUE TITLE
Prepare project for Jakarta EE 8 release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/javamail#385]
### Tasks

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.
